#! /bin/bash

# WSL のインスタンスが終了しないようにする

__setup-wsl-keepalive() {
    __read_prompt 'setup WSL keepalive? (y)' yn
    if [ "$yn" != 'y' ]; then
        echo 'abort.'
        return
    fi

    # https://github.com/microsoft/WSL/issues/8854
    sudo cp $(dirname $BASH_SOURCE)/../lib/wsl-keepalive.service /etc/systemd/system/wsl-keepalive.service
    sudo systemctl enable wsl-keepalive.service
    sudo systemctl start wsl-keepalive.service
}

if [ -f /etc/wsl.conf ]; then
    if [ ! -e /etc/systemd/system/wsl-keepalive.service ]; then
        __setup-wsl-keepalive
    fi
fi

unset -f __setup-wsl-keepalive
